# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: alpine:3.7
#     steps:
#       - run:
#           name: The First Step
#           command: |
#             echo 'Hello World!'
#             echo 'This is the delivery pipeline'

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
version: 2.1

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          profile-name: default
          region: AWS_REGION_ENV_VAR_NAME
          repo: ricardo21/supermarketclient
          skip-when-tags-exist: false
          tag: 'latest'
          # tag: "$CIRCLE_BUILD_NUM"