jobs: 
  verify-deployment: 
    docker: 
      - 
        image: "circleci/python:3.7.1"
    steps: 
      - aws-cli/install
      - 
        aws-cli/configure: 
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          aws-region: AWS_REGION_ENV_VAR_NAME
      - 
        run: 
          command: |
              TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                  --task-definition ecs-service-1 \
                  --output text \
                  --query 'taskDefinition.taskDefinitionArn')
              echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >> $BASH_ENV
          name: "Get last task definition"
      - 
        aws-ecs/verify-revision-is-deployed: 
          cluster-name: ecs-cluster-1
          family: ecs-service-1
          task-definition-arn: "${TASK_DEFINITION_ARN}"
orbs: 
  aws-cli: circleci/aws-cli@0.1.4
  aws-ecs: circleci/aws-ecs@0.0.3
version: 2.1
workflows: 
  test-workflow: 
    jobs: 
      - verify-deployment

# version: 2.1
# orbs:
#   aws-cli: circleci/aws-cli@0.1.4
#   aws-ecr: circleci/aws-ecr@6.5.0
#   aws-ecs: circleci/aws-ecs@0.0.10
# workflows:
#   build-and-deploy:
#     jobs:
#       # - aws-ecr/build-and-push-image:
#       #     account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
#       #     aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
#       #     aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
#       #     repo: supermarketclient
#       #     region: AWS_REGION_ENV_VAR_NAME
#       #     tag: 'latest'

#       - aws-ecs/deploy-service-update:
#           # requires:
#           #   - aws-ecr/build-and-push-image
#           aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
#           aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
#           family: "ecs-service-1"
#           cluster-name: "ecs-cluster-1"
#           container-image-name-updates: "container=ecs-service-1,tag=2"
# orbs:
#   aws-ecr: circleci/aws-ecr@6.12.2
# version: 2.1

# workflows:
#   build_and_push_image:
#     jobs:
#       - aws-ecr/build-and-push-image:
#           account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
#           aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
#           aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
#           create-repo: true
#           dockerfile: Dockerfile
#           no-output-timeout: 20m
#           path: .
#           profile-name: default
#           region: AWS_REGION_ENV_VAR_NAME
#           repo: supermarketclient
#           skip-when-tags-exist: false
#           tag: 'latest'
