version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.4
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  build_and_push_image:
    jobs:
      - verify-deployment: null
        docker:
          - image: 'circleci/python:3.7.1'
        steps:
          - aws-cli/install
          - aws-cli/configure:
              aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
              aws-region: AWS_DEFAULT_REGION
          - run:
              name: Get last task definition
              command: |
                TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                    --task-definition ecs-service-1 \
                    --output text \
                    --query 'taskDefinition.taskDefinitionArn')
                echo "export TASK_DEFINITION_ARN=ecs-task-1" >> $BASH_ENV
          - aws-ecs/verify-revision-is-deployed:
              family: ecs-service-1
              cluster-name: ecs-cluster-1
              task-definition-arn: ecs-task-1
      - aws-ecs/deploy-service-update:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          aws-region: AWS_DEFAULT_REGION
          family: ecs-service-1
          cluster-name: ecs-cluster-1
          container-image-name-updates: 'container=ecs-service-1,tag=latest'